name: deploy-wallet-app

on:
  push:
    branches:
      - main
    paths:
      - '10_frontend/wallet_webapp/**'

jobs:
  deploy-wallet-app:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: 'arn:aws:iam::594175341170:role/github-oidc-role'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node01
        run: cd 10_frontend/wallet_webapp
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Setup node02
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install package
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          aws s3 sync --region ap-northeast-1 ./out s3://awswebapphoststack-trustbankwebbucket4c073bc3-eeusxyhpkjpk --delete --size-only
          aws cloudfront create-invalidation --region ap-northeast-1 --distribution-id E23WG2G5PBNFKD --paths "/*"
